### ISSUE TITLE
user mode not work

### ISSUE THREAD

**Issue by anlo1220** [xditya/ChannelAutoPost#19]
user mode not work

**Comment by xditya** [comment]
Please provide the traceback.

**Comment by anlo1220** [comment]
it show

```
root@debian:~/ChannelAutoPost-user# python3 bot.py
Starting...
Bot has started.
```
but does not foward any message

**Comment by xditya** [comment]
Verify the below:
- Is the (user)bot admin in the To chat?
- are the chat IDs correct?
- is a new message posted in the from chat?

If you think it's all good, share your environment variables (the from chat ID and to chat ID - to be precise)

**Comment by anlo1220** [comment]
1. Is the (user)bot admin in the To chat?
This channel is created by me for testing and I am the admin 
2. are the chat IDs correct?
yes
3. is a new message posted in the from chat?
yes

```
APP_ID=28065xxx
API_HASH=e0da17f05c73dc2b558f8023781a5xxx
FROM_CHANNEL=-18480505xx
TO_CHANNEL=-17571381xx
SESSION=1BVtsOGkBu1lqAqvQ66pDeoCA1BgY35iHDxWUEAbVsh5oySNGweWUqX4ahLFafpot0tTEhmiE10AcS4EcsfXySTBEe07QgSPRvvsy_JDaS0y-M-qB9LFHRmBH7wNfvXQjW1FsdqegCIelcaP1JR8MnsRQ5__WX4TCn8qqXIM2eZgad8sn4OvPAySEKxlUXORszy8RzmLpcERtAuR2euuc-ZAkzqk9ji5ThK9LAyx--Vezv8qW_CbU67pe2YzSr8bygnVxVA7OVPXDu2nmkAuHtnGMQHP1aLPBXD559IqRvHmf2WWz7VleGP1TLUwSIlrtE5m46TRmMabLPBTqcbgKxw0G_lysxxx=
```

**Comment by xditya** [comment]
Please enable "view history for new members" in the from and to chat (this makes it a supergroup). Now, you'd get the chat IDs as -100xxx. Add that to your FROM_CHANNEL and TO_CHANNEL

> **Note**
adding -100 to the existing IDs might work, if the groups are already a supergroup, you can try either way and let me know the outcome.

**Comment by anlo1220** [comment]
I try chanel and group in the from and to chat .but still does not work.

**Comment by xditya** [comment]
Please contact me on https://BotzHubChat.t.me
